# yaml-language-server: $schema=https://blue-build.org
name: bluebuild-bib
description: My feature-separated custom Fedora Kinoite image.
base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest

modules:
  - type: containerfile
    containerfiles:
      - custom

  # 2. Automation for your system-wide flatpaks
  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.mozilla.firefox
          - org.gnome.Loupe

  # 3. Secure cryptographical signing for your custom image
  - type: signing
